services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app-frontend
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - "3333:3333"
    working_dir: /app-backend
    volumes:
      - ./backend/src:/app-backend/src
    env_file:
      - path: ./backend/.env
